server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fsdb00
    username: farmastock_db
    password: fs1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        open-in-view: false
    show-sql: true

    logging:
      level:
        org.hibernate.SQL: debug